server:
  port: 8080
spring:
  application:
    name: ClearSolutions Test Task
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: clearsolutions
    password: clearsolutions
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql

constants:
  min-user-age: 18


